export const RATES = [
  {
    curricolum_id: '5',
    class_scope: 1,
    tuition: 700,
    rate: 350,
    bonus: 0,
  },
  {
    curricolum_id: '5',
    class_scope: 2,
    tuition: 400,
    rate: 350,
    bonus: 50,
  },
  {
    curricolum_id: '5',
    class_scope: 3,
    tuition: 350,
    rate: 350,
    bonus: 100,
  },
  {
    curricolum_id: '5',
    class_scope: 4,
    tuition: 350,
    rate: 350,
    bonus: 150,
  },
  {
    curricolum_id: '5',
    class_scope: 5,
    tuition: 300,
    rate: 350,
    bonus: 200,
  },
  {
    curricolum_id: '5',
    class_scope: 6,
    tuition: 300,
    rate: 350,
    bonus: 250,
  },
  {
    curricolum_id: '4',
    class_scope: 1,
    tuition: 700,
    rate: 350,
    bonus: 0,
  },
  {
    curricolum_id: '4',
    class_scope: 2,
    tuition: 400,
    rate: 350,
    bonus: 50,
  },
  {
    curricolum_id: '4',
    class_scope: 3,
    tuition: 350,
    rate: 350,
    bonus: 100,
  },
  {
    curricolum_id: '4',
    class_scope: 4,
    tuition: 350,
    rate: 350,
    bonus: 150,
  },
  {
    curricolum_id: '4',
    class_scope: 5,
    tuition: 300,
    rate: 350,
    bonus: 200,
  },
  {
    curricolum_id: '4',
    class_scope: 6,
    tuition: 300,
    rate: 350,
    bonus: 250,
  },
  {
    curricolum_id: '3',
    class_scope: 1,
    tuition: 600,
    rate: 300,
    bonus: 0,
  },
  {
    curricolum_id: '3',
    class_scope: 2,
    tuition: 350,
    rate: 300,
    bonus: 50,
  },
  {
    curricolum_id: '3',
    class_scope: 3,
    tuition: 300,
    rate: 300,
    bonus: 100,
  },
  {
    curricolum_id: '3',
    class_scope: 4,
    tuition: 300,
    rate: 300,
    bonus: 150,
  },
  {
    curricolum_id: '3',
    class_scope: 5,
    tuition: 250,
    rate: 300,
    bonus: 200,
  },
  {
    curricolum_id: '3',
    class_scope: 6,
    tuition: 250,
    rate: 300,
    bonus: 250,
  },
  {
    curricolum_id: '2',
    class_scope: 1,
    tuition: 700,
    rate: 350,
    bonus: 0,
  },
  {
    curricolum_id: '2',
    class_scope: 2,
    tuition: 400,
    rate: 350,
    bonus: 50,
  },
  {
    curricolum_id: '2',
    class_scope: 3,
    tuition: 350,
    rate: 350,
    bonus: 100,
  },
  {
    curricolum_id: '2',
    class_scope: 4,
    tuition: 350,
    rate: 350,
    bonus: 150,
  },
  {
    curricolum_id: '2',
    class_scope: 5,
    tuition: 300,
    rate: 350,
    bonus: 200,
  },
  {
    curricolum_id: '2',
    class_scope: 6,
    tuition: 300,
    rate: 350,
    bonus: 250,
  },
  {
    curricolum_id: '1',
    class_scope: 1,
    tuition: 600,
    rate: 300,
    bonus: 0,
  },
  {
    curricolum_id: '1',
    class_scope: 2,
    tuition: 350,
    rate: 300,
    bonus: 50,
  },
  {
    curricolum_id: '1',
    class_scope: 3,
    tuition: 300,
    rate: 300,
    bonus: 100,
  },
  {
    curricolum_id: '1',
    class_scope: 4,
    tuition: 300,
    rate: 300,
    bonus: 150,
  },
  {
    curricolum_id: '1',
    class_scope: 5,
    tuition: 250,
    rate: 300,
    bonus: 200,
  },
  {
    curricolum_id: '1',
    class_scope: 6,
    tuition: 250,
    rate: 300,
    bonus: 250,
  },
];

export const CLASS_TYPES = [
  { value: 1, label: 'Lớp kế hoạch' },
  { value: 2, label: 'Lớp phát sinh' },
];

export const SUBJECTS = [
  { value: '1', label: 'Math' },
  { value: '2', label: 'Physics' },
  { value: '3', label: 'Chemistry' },
  { value: '4', label: 'Biology' },
  { value: '5', label: 'Business' },
  { value: '6', label: 'Econ' },
  { value: '7', label: 'Computer science' },
  { value: '8', label: 'English' },
];

export const CURRICOLUMS = [
  { value: '1', label: 'IGCSE classes' },
  { value: '2', label: 'A-level classes' },
  { value: '3', label: 'Academic English (IELTS, TOEFL)' },
  { value: '4', label: 'IB, AP classes' },
  { value: '5', label: 'Academic English ( SAT)' },
];

export const TRANSACTION_TYPE = {
  TEACHER: 1,
  STUDENT: 2,
  OTHER: 3,
};

export const KES_ROLE = {
  ADMIN: 'KES_ADMIN',
  TEACHER: 'KES_TEACHER',
  STUDENT: 'KES_STUDENT',
};
